---
- name: 'Wait for API port to be available'
  wait_for:
    port: '{{ gitea_app_cont_web_port }}'
    delay: 5
    sleep: 5
    timeout: 60

- name: Check if admin user already exists
  register: gitea_admin_users_cmd
  command: |
    docker exec --user {{ gitea_app_cont_uid }} -i {{ gitea_app_cont_name }} \
      gitea admin user list --admin

- name: Create main Gitea admin user
  when: gitea_admin_users_cmd.stdout is not search('(?m)^\s*\d+\s+' ~ gitea_app_admin_user ~ '\s')
  command: |
    docker exec --user {{ gitea_app_cont_uid }} -i {{ gitea_app_cont_name }} \
      gitea admin user create --admin \
        --username '{{ gitea_app_admin_user | mandatory }}' \
        --password '{{ gitea_app_admin_pass | mandatory }}' \
        --email '{{ gitea_app_admin_email | mandatory }}' \
        --must-change-password=false
