---
- name: Create compose file
  template:
    src: 'docker-compose.yml.j2'
    dest: '{{ gitea_compose_file }}'
    owner: 'dockremap'
    group: 'docker'
    mode: 0640

- name: Create containers
  community.docker.docker_compose_v2:
    project_src: '{{ gitea_service_path }}'
    pull:        '{{ compose_pull }}'
    recreate:     '{{ gitea_config.changed | ternary("always", compose_recreate) }}'
  register: gitea_container
