---
- name: Copy init script
  template:
    src: 'init-registry-org.py.j2'
    dest: '{{ gitea_service_path }}/init-registry-org.py'
    owner: '{{ gitea_app_host_uid }}'
    group: docker
    mode: 0770

- name: Launch init script
  command: |
    {{ gitea_service_path }}/init-registry-org.py \
      --org "{{ gitea_organizations | join(',') }}" \
      --url "http://localhost:{{ gitea_app_cont_web_port }}"
  environment:
      GITEA_USERNAME: '{{ gitea_app_admin_user }}'
      GITEA_PASSWORD: '{{ gitea_app_admin_pass }}'
  when: gitea_organizations is defined and gitea_organizations|length > 0
