---
- import_tasks: config.yml
  tags: ['role::gitea', 'role::gitea:config']
- import_tasks: compose.yml
  tags: ['role::gitea', 'role::gitea:compose']
- import_tasks: admin.yml
  tags: ['role::gitea', 'role::gitea:admin']
- import_tasks: token.yml
  tags: ['role::gitea', 'role::gitea:token']
- import_tasks: backup.yml
  tags: ['role::gitea', 'role::gitea:backup']
- import_tasks: consul.yml
  tags: ['role::gitea', 'role::gitea:consul']
- import_tasks: init.yml
  tags: ['role::gitea', 'role::gitea:init']
- import_tasks: cleanup.yml
  tags: ['role::gitea', 'role::gitea:cleanup']
